# Generated by Django 4.2.7 on 2026-06-07 00:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=100, unique=True, verbose_name='器材编号')),
                ('name', models.CharField(max_length=200, verbose_name='器材名称')),
                ('specification', models.CharField(blank=True, max_length=200, null=True, verbose_name='规格型号')),
                ('purchase_date', models.DateField(blank=True, null=True, verbose_name='采购日期')),
                ('damage_level', models.IntegerField(choices=[(0, '无损坏'), (1, '轻微损坏'), (2, '中度损坏'), (3, '严重损坏'), (4, '报废')], default=0, verbose_name='损坏等级')),
                ('is_available', models.BooleanField(default=True, verbose_name='是否可用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '器材',
                'verbose_name_plural': '器材',
                'db_table': 'equipment',
            },
        ),
        migrations.CreateModel(
            name='EquipmentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='类型名称')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='类型编码')),
                ('description', models.TextField(blank=True, null=True, verbose_name='描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '器材类型',
                'verbose_name_plural': '器材类型',
                'db_table': 'equipment_type',
            },
        ),
        migrations.CreateModel(
            name='PatrolBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_no', models.CharField(max_length=50, unique=True, verbose_name='批次号')),
                ('upload_time', models.DateTimeField(auto_now_add=True, verbose_name='上传时间')),
                ('total_count', models.IntegerField(default=0, verbose_name='总记录数')),
                ('success_count', models.IntegerField(default=0, verbose_name='成功入库数')),
                ('problem_count', models.IntegerField(default=0, verbose_name='问题记录数')),
                ('file_name', models.CharField(max_length=255, verbose_name='文件名')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('uploader', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='uploaded_batches', to=settings.AUTH_USER_MODEL, verbose_name='上传人')),
            ],
            options={
                'verbose_name': '巡管批次',
                'verbose_name_plural': '巡管批次',
                'db_table': 'patrol_batch',
                'ordering': ['-upload_time'],
            },
        ),
        migrations.CreateModel(
            name='StorageLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='库位名称')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='库位编码')),
                ('area', models.CharField(max_length=100, verbose_name='区域')),
                ('description', models.TextField(blank=True, null=True, verbose_name='描述')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '库位',
                'verbose_name_plural': '库位',
                'db_table': 'storage_location',
            },
        ),
        migrations.CreateModel(
            name='ProblemRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_number', models.IntegerField(verbose_name='行号')),
                ('problem_type', models.CharField(choices=[('missing_serial', '器材编号缺失'), ('invalid_location', '库位不存在'), ('time_inversion', '借用时间倒置'), ('return_conflict', '归还状态冲突'), ('damage_out_of_range', '损坏等级越界'), ('equipment_not_found', '器材不存在'), ('other', '其他')], max_length=30, verbose_name='问题类型')),
                ('problem_detail', models.TextField(verbose_name='问题详情')),
                ('row_data', models.JSONField(verbose_name='原始行数据')),
                ('is_resolved', models.BooleanField(default=False, verbose_name='是否已解决')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='处理时间')),
                ('resolution_note', models.TextField(blank=True, null=True, verbose_name='处理备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='problem_records', to='core.patrolbatch', verbose_name='所属批次')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='resolved_problems', to=settings.AUTH_USER_MODEL, verbose_name='处理人')),
            ],
            options={
                'verbose_name': '问题记录',
                'verbose_name_plural': '问题记录',
                'db_table': 'problem_record',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PatrolRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_number', models.IntegerField(verbose_name='行号')),
                ('equipment_serial', models.CharField(max_length=100, verbose_name='器材编号')),
                ('equipment_name', models.CharField(max_length=200, verbose_name='器材名称')),
                ('location_code', models.CharField(max_length=50, verbose_name='库位编码')),
                ('borrower', models.CharField(max_length=100, verbose_name='借用人')),
                ('borrow_date', models.DateField(verbose_name='借用日期')),
                ('due_date', models.DateField(verbose_name='应还日期')),
                ('return_date', models.DateField(blank=True, null=True, verbose_name='归还日期')),
                ('is_returned', models.BooleanField(default=False, verbose_name='是否归还')),
                ('damage_level', models.IntegerField(choices=[(0, '无损坏'), (1, '轻微损坏'), (2, '中度损坏'), (3, '严重损坏'), (4, '报废')], default=0, verbose_name='损坏等级')),
                ('damage_description', models.TextField(blank=True, null=True, verbose_name='损坏描述')),
                ('status', models.CharField(choices=[('pending', '待复核'), ('approved', '已通过'), ('rejected', '已驳回')], default='pending', max_length=20, verbose_name='状态')),
                ('review_time', models.DateTimeField(blank=True, null=True, verbose_name='复核时间')),
                ('review_remark', models.TextField(blank=True, null=True, verbose_name='复核备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='core.patrolbatch', verbose_name='所属批次')),
                ('equipment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='patrol_records', to='core.equipment', verbose_name='器材')),
                ('equipment_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='patrol_records', to='core.equipmenttype', verbose_name='器材类型')),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reviewed_records', to=settings.AUTH_USER_MODEL, verbose_name='复核人')),
                ('storage_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='patrol_records', to='core.storagelocation', verbose_name='库位')),
            ],
            options={
                'verbose_name': '巡管记录',
                'verbose_name_plural': '巡管记录',
                'db_table': 'patrol_record',
                'ordering': ['-id'],
            },
        ),
        migrations.AddField(
            model_name='equipment',
            name='equipment_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='equipments', to='core.equipmenttype', verbose_name='器材类型'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='storage_location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='equipments', to='core.storagelocation', verbose_name='库位'),
        ),
        migrations.CreateModel(
            name='BorrowRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='规则名称')),
                ('max_borrow_days', models.IntegerField(verbose_name='最大借用天数')),
                ('max_borrow_quantity', models.IntegerField(default=1, verbose_name='最大借用数量')),
                ('requires_approval', models.BooleanField(default=False, verbose_name='是否需要审批')),
                ('description', models.TextField(blank=True, null=True, verbose_name='描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('equipment_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='borrow_rules', to='core.equipmenttype', verbose_name='器材类型')),
            ],
            options={
                'verbose_name': '借用规则',
                'verbose_name_plural': '借用规则',
                'db_table': 'borrow_rule',
            },
        ),
    ]
