# Generated by Django 4.2.7 on 2026-06-07 01:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentRepairOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_no', models.CharField(max_length=50, unique=True, verbose_name='工单号')),
                ('repair_reason', models.CharField(choices=[('normal_wear', '正常损耗'), ('accident', '意外损坏'), ('malfunction', '设备故障'), ('maintenance', '定期维护'), ('other', '其他')], max_length=30, verbose_name='维修原因')),
                ('damage_description', models.TextField(verbose_name='损坏描述')),
                ('send_time', models.DateTimeField(verbose_name='送修时间')),
                ('expected_complete_time', models.DateTimeField(blank=True, null=True, verbose_name='预计完成时间')),
                ('actual_complete_time', models.DateTimeField(blank=True, null=True, verbose_name='实际完成时间')),
                ('status', models.CharField(choices=[('pending', '待维修'), ('repairing', '维修中'), ('completed', '已完成'), ('cancelled', '已取消')], default='pending', max_length=20, verbose_name='处理状态')),
                ('result_note', models.TextField(blank=True, null=True, verbose_name='结果说明')),
                ('updated_damage_level', models.IntegerField(blank=True, choices=[(0, '无损坏'), (1, '轻微损坏'), (2, '中度损坏'), (3, '严重损坏'), (4, '报废')], null=True, verbose_name='维修后损坏等级')),
                ('restore_available', models.BooleanField(default=True, verbose_name='恢复可用状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_repair_orders', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='repair_orders', to='core.equipment', verbose_name='器材')),
                ('patrol_record', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='repair_orders', to='core.patrolrecord', verbose_name='巡管记录')),
                ('repair_person', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assigned_repairs', to=settings.AUTH_USER_MODEL, verbose_name='维修负责人')),
            ],
            options={
                'verbose_name': '器材维修工单',
                'verbose_name_plural': '器材维修工单',
                'db_table': 'equipment_repair_order',
                'ordering': ['-created_at'],
            },
        ),
    ]
