# Generated by Django 4.2.7 on 2026-06-07 02:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0002_equipmentrepairorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='patrolrecord',
            name='overdue_handle_remark',
            field=models.TextField(blank=True, null=True, verbose_name='逾期处理备注'),
        ),
        migrations.AddField(
            model_name='patrolrecord',
            name='overdue_handle_status',
            field=models.CharField(choices=[('pending', '待处理'), ('handled', '已处理')], default='pending', max_length=20, verbose_name='逾期处理状态'),
        ),
        migrations.AddField(
            model_name='patrolrecord',
            name='overdue_handled_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='逾期处理时间'),
        ),
        migrations.AddField(
            model_name='patrolrecord',
            name='overdue_handled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='handled_overdue_records', to=settings.AUTH_USER_MODEL, verbose_name='逾期处理人'),
        ),
    ]
