# Generated by Django 4.2.7 on 2026-06-07 07:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0004_fix_overdue_handle_status_semantics'),
    ]

    operations = [
        migrations.AddField(
            model_name='patrolrecord',
            name='return_damage_level',
            field=models.IntegerField(blank=True, choices=[(0, '无损坏'), (1, '轻微损坏'), (2, '中度损坏'), (3, '严重损坏'), (4, '报废')], null=True, verbose_name='归还损坏等级'),
        ),
        migrations.AddField(
            model_name='patrolrecord',
            name='return_remark',
            field=models.TextField(blank=True, null=True, verbose_name='归还说明'),
        ),
        migrations.AddField(
            model_name='patrolrecord',
            name='return_storage_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='returned_patrol_records', to='core.storagelocation', verbose_name='归还库位'),
        ),
        migrations.AddField(
            model_name='patrolrecord',
            name='returned_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='归还登记时间'),
        ),
        migrations.AddField(
            model_name='patrolrecord',
            name='returned_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='returned_records', to=settings.AUTH_USER_MODEL, verbose_name='归还登记人'),
        ),
        migrations.AlterField(
            model_name='patrolrecord',
            name='location_code',
            field=models.CharField(max_length=50, verbose_name='原库位编码'),
        ),
        migrations.AlterField(
            model_name='patrolrecord',
            name='storage_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='patrol_records', to='core.storagelocation', verbose_name='原库位'),
        ),
    ]
